const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#FF4444",
    background: "#0A0A0A",
    foreground: "#FFFFFF",
    card: "#1A1A1A",
    cardForeground: "#FFFFFF",
    primary: "#FF4444",
    primaryForeground: "#FFFFFF",
    secondary: "#2A2A2A",
    secondaryForeground: "#FFFFFF",
    muted: "#2A2A2A",
    mutedForeground: "#888888",
    accent: "#FF6600",
    accentForeground: "#FFFFFF",
    destructive: "#FF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#1A1A1A",
    ai: "#4488FF",
    success: "#44FF88",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FF4444",
    background: "#0A0A0A",
    foreground: "#FFFFFF",
    card: "#1A1A1A",
    cardForeground: "#FFFFFF",
    primary: "#FF4444",
    primaryForeground: "#FFFFFF",
    secondary: "#2A2A2A",
    secondaryForeground: "#FFFFFF",
    muted: "#2A2A2A",
    mutedForeground: "#888888",
    accent: "#FF6600",
    accentForeground: "#FFFFFF",
    destructive: "#FF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#1A1A1A",
    ai: "#4488FF",
    success: "#44FF88",
  },
  radius: 12,
};

export default colors;
